import type { DashboardWidgetLibraryEntry } from './types'

export const WIDGET_LIBRARY: DashboardWidgetLibraryEntry[] = [
  {
    id: 'lib-revenue',
    title: 'Revenue',
    description: 'Total sales for the selected period',
    category: 'commerce',
    type: 'kpi',
    icon: 'dollar-sign',
    recommended: true,
    metricId: 'commerce_revenue',
    dataSource: 'commerce',
    drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
  },
  {
    id: 'lib-orders',
    title: 'Orders',
    description: 'Track total orders and compare with previous period',
    category: 'commerce',
    type: 'kpi',
    icon: 'shopping-cart',
    recommended: true,
    metricId: 'commerce_orders',
    dataSource: 'commerce',
    drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
  },
  {
    id: 'lib-revenue-over-time',
    title: 'Revenue over time',
    description: 'Daily revenue trend compared with previous period',
    category: 'commerce',
    type: 'timeseries',
    icon: 'line-chart',
    recommended: true,
    metricId: 'commerce_revenue_over_time',
    dataSource: 'commerce',
    chartVariant: 'area',
    drilldown: { routeName: 'OrdersReport', label: 'Open orders report' },
  },
  {
    id: 'lib-top-products',
    title: 'Top products',
    description: 'Best performing products by revenue or units sold',
    category: 'commerce',
    type: 'table',
    icon: 'package',
    metricId: 'commerce_recent_orders',
    dataSource: 'commerce',
    drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
  },
  {
    id: 'lib-open-rate',
    title: 'Open rate',
    description: 'Email open rate across campaigns',
    category: 'marketing',
    type: 'kpi',
    icon: 'mail-open',
    recommended: true,
    metricId: 'marketing_open_rate',
    dataSource: 'marketing',
    drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
  },
  {
    id: 'lib-campaign-activity',
    title: 'Campaign activity',
    description: 'Recent sends, updates, and campaign events',
    category: 'marketing',
    type: 'activity',
    icon: 'activity',
    metricId: 'marketing_live_activity',
    dataSource: 'marketing',
    drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
  },
  {
    id: 'lib-total-contacts',
    title: 'Total contacts',
    description: 'Total contacts and growth over time',
    category: 'marketing',
    type: 'kpi',
    icon: 'contact-round',
    recommended: true,
    metricId: 'contacts_total',
    dataSource: 'contacts',
    drilldown: { routeName: 'AllContacts', label: 'Open all contacts' },
  },
  {
    id: 'lib-open-tickets',
    title: 'Open tickets',
    description: 'Track open support requests and SLA risk',
    category: 'service',
    type: 'kpi',
    icon: 'inbox',
    metricId: 'service_open_tickets',
    dataSource: 'service',
    drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
  },
  {
    id: 'lib-retail-revenue',
    title: 'Retail revenue',
    description: 'Gross POS revenue for the selected period',
    category: 'retail',
    type: 'kpi',
    icon: 'dollar-sign',
    recommended: true,
    metricId: 'retail_revenue',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail revenue' },
  },
  {
    id: 'lib-retail-sale-count',
    title: 'Sale count',
    description: 'Completed POS sale transactions',
    category: 'retail',
    type: 'kpi',
    icon: 'receipt',
    metricId: 'retail_sale_count',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail sales' },
  },
  {
    id: 'lib-retail-customer-count',
    title: 'Customer count',
    description: 'Unique customers who made a purchase',
    category: 'retail',
    type: 'kpi',
    icon: 'users',
    metricId: 'retail_customer_count',
    dataSource: 'retail',
    drilldown: { routeName: 'AllContacts', label: 'Retail customers' },
  },
  {
    id: 'lib-retail-gross-profit',
    title: 'Gross profit',
    description: 'Revenue minus cost of goods sold',
    category: 'retail',
    type: 'kpi',
    icon: 'trending-up',
    recommended: true,
    metricId: 'retail_gross_profit',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail profit' },
  },
  {
    id: 'lib-retail-discounted',
    title: 'Discounted',
    description: 'Total discount value applied across sales',
    category: 'retail',
    type: 'kpi',
    icon: 'tag',
    metricId: 'retail_discounted',
    dataSource: 'retail',
    drilldown: { routeName: 'Coupons', label: 'Coupons & discounts' },
  },
  {
    id: 'lib-retail-discounted-pct',
    title: 'Discounted (%)',
    description: 'Share of revenue lost to discounts',
    category: 'retail',
    type: 'kpi',
    icon: 'percent',
    metricId: 'retail_discounted_pct',
    dataSource: 'retail',
    drilldown: { routeName: 'Coupons', label: 'Coupons & discounts' },
  },
  {
    id: 'lib-retail-avg-sale-value',
    title: 'Avg sale value',
    description: 'Average value per completed sale',
    category: 'retail',
    type: 'kpi',
    icon: 'shopping-cart',
    metricId: 'retail_avg_sale_value',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail basket size' },
  },
  {
    id: 'lib-retail-avg-items-per-sale',
    title: 'Avg items / sale',
    description: 'Average items per completed sale',
    category: 'retail',
    type: 'kpi',
    icon: 'package',
    metricId: 'retail_avg_items_per_sale',
    dataSource: 'retail',
    drilldown: { routeName: 'ProductsList', label: 'Retail product mix' },
  },
]
