import type { DashboardWidgetLibraryEntry } from './types'

export const WIDGET_LIBRARY: DashboardWidgetLibraryEntry[] = [
  {
    id: 'lib-revenue',
    title: 'Revenue',
    description: 'Total sales for the selected period',
    category: 'commerce',
    type: 'kpi',
    icon: 'dollar-sign',
    recommended: true,
    metricId: 'commerce_revenue',
    dataSource: 'commerce',
    drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
  },
  {
    id: 'lib-orders',
    title: 'Orders',
    description: 'Track total orders and compare with previous period',
    category: 'commerce',
    type: 'kpi',
    icon: 'shopping-cart',
    recommended: true,
    metricId: 'commerce_orders',
    dataSource: 'commerce',
    drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
  },
  {
    id: 'lib-revenue-over-time',
    title: 'Revenue over time',
    description: 'Daily revenue trend compared with previous period',
    category: 'commerce',
    type: 'timeseries',
    icon: 'line-chart',
    recommended: true,
    metricId: 'commerce_revenue_over_time',
    dataSource: 'commerce',
    chartVariant: 'area',
    drilldown: { routeName: 'OrdersReport', label: 'Open orders report' },
  },
  {
    id: 'lib-top-products',
    title: 'Top products',
    description: 'Best performing products by revenue or units sold',
    category: 'commerce',
    type: 'table',
    icon: 'package',
    metricId: 'commerce_recent_orders',
    dataSource: 'commerce',
    drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
  },
  {
    id: 'lib-open-rate',
    title: 'Open rate',
    description: 'Email open rate across campaigns',
    category: 'marketing',
    type: 'kpi',
    icon: 'mail-open',
    recommended: true,
    metricId: 'marketing_open_rate',
    dataSource: 'marketing',
    drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
  },
  {
    id: 'lib-campaign-activity',
    title: 'Campaign activity',
    description: 'Recent sends, updates, and campaign events',
    category: 'marketing',
    type: 'activity',
    icon: 'activity',
    metricId: 'marketing_live_activity',
    dataSource: 'marketing',
    drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
  },
  {
    id: 'lib-total-contacts',
    title: 'Total contacts',
    description: 'Total contacts and growth over time',
    category: 'marketing',
    type: 'kpi',
    icon: 'contact-round',
    recommended: true,
    metricId: 'contacts_total',
    dataSource: 'contacts',
    drilldown: { routeName: 'AllContacts', label: 'Open all contacts' },
  },
  {
    id: 'lib-open-tickets',
    title: 'Open tickets',
    description: 'Track open support requests and SLA risk',
    category: 'service',
    type: 'kpi',
    icon: 'inbox',
    metricId: 'service_open_tickets',
    dataSource: 'service',
    drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
  },
]
